### ISSUE TITLE
actionTitleLabel access level

### ISSUE THREAD

**Issue by Maryom** [xmartlabs/XLActionController#114]
Hey,

Thanks for your awesome repo.

I just have a suggestion. I need to customize the `actionTitleLabel` so can I pull a request to make `actionTitleLabel` public?

As I tried and I got:
`'actionTitleLabel' is inaccessible due to 'internal' protection level`

**Comment by mats-claassen** [comment]
The `actionTitleLabel` of `ActionCell` is `open`. Which `actionTitleLabel ` are you talking about?

**Comment by Maryom** [comment]
What I meant is:

`@IBOutlet weak var actionTitleLabel: UILabel!`

In `SkypeCell` class.

Thanks.

**Comment by mats-claassen** [comment]
Yes, you can submit a PR to fix that

**Comment by Maryom** [comment]
Hello,

I think we have to bump the pod version so that the changes appear to users.
