### ISSUE TITLE
Support for Swift 5

### ISSUE THREAD

**Issue by ascentman** [xmartlabs/XLActionController#116]
**Environment**
- Xcode Version: 10.2
- Swift Version: 5

**Goals**
Swift 5 support for the framework

**Expected Results**
No warning to convert XLActionControllerto to Swift 5

**Actual Results**
Xcode created warnings to convert XLActionControllerto to Swift 5

**Steps to Reproduce**
Build the cocoapod in Xcode 10.2

**Code Samples & Details**
Run any project depending on the pod's in Xcode 10.2 to see the warning.

**Comment by mats-claassen** [comment]
Done
