### ISSUE TITLE
crash on rotation

### ISSUE THREAD

**Issue by spotby** [xmartlabs/XLActionController#12]
I'm getting a crash on rotation at line 49 in ActionCell.swift.
      actionTitleLabelConstraintToImageView?.priority = UILayoutPriorityDefaultHigh

the error I'm getting is:

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Mutating a priority from required to not on an installed constraint (or vice-versa) is not supported.  You passed priority 1000 and the existing priority was 1000.'
*** First throw call stack:

**Comment by nkmadala** [comment]
I'm also facing the same issue. Were you able to fix this?
