### ISSUE TITLE
Xcode 11

### ISSUE THREAD

**Issue by Legasquare90** [xmartlabs/XLActionController#127]
I'm using the last release of XLActionController, but compilation is failing due to an issue with the file "ActionCell.xib". In your last commit, you solve this problem (I've copied the file to my project and works fine with it), but I prefer to use the last releases of XLActionController that I can find in CocoaPods without to worry about changes. Could you upload these last changes to a new release? Thank you!!

**Comment by JGVB** [comment]
@Puasonych @mats-claassen Any update on this? 5.0.1?!

**Comment by Puasonych** [comment]
@mats-claassen suggested waiting for the release of Xcode 11. It was released yesterday 🙃. Time to release 5.0.1 🤗

**Comment by mats-claassen** [comment]
You can expect a release this week. If you don't like pointing to master branch you can point to a specific commit in the Podfile

**Comment by Legasquare90** [comment]
@mats-claassen Thank you for the advice to point to a specific commit! I didn't know it! I'll do that until you create the new release =)

For the rest of the people, I'll leave here the pod line to fix the xcode 11 issue:
`pod 'XLActionController', :git => 'https://github.com/xmartlabs/XLActionController.git', :commit => 'e26395bb8500a72a87cbb00ad1dace623ec0984f'`

**Comment by mats-claassen** [comment]
Version 5.0.1 released!
