### ISSUE TITLE
how to add image to periscopeExample??? 

### ISSUE THREAD

**Issue by shindonghyeok** [xmartlabs/XLActionController#14]
how can i add image to periscopeExample as a youtube...??

**Comment by m-revetria** [comment]
@shindonghyeok:

You need to do few changes to add an image to the periscope's cell:

1. Modify the PeriscopeCell included in the Example project. First add an image view in the xib file and then add an outlet to `ActionCell.actionImageView`. 
2. Next you have to change the declaration of `PeriscopeActionController` and `PeriscopeSection` by passing `ActionData` as `ActionDataType`, they will look like

   ```swift
   public class PeriscopeSection: Section<ActionData, Void> {
   // ...
   }

   public class PeriscopeActionController: ActionController<PeriscopeCell, ActionData, PeriscopeHeader, String, UICollectionReusableView, Void> {
   // ...
   }
   ```
3. The last step is pass the image to the cell setup method in the `PeriscopeActionController.init` method:
   ```swift
   public override init(nibName nibNameOrNil: String? = nil, bundle nibBundleOrNil: NSBundle? = nil) {
           super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)

           // Other stuff  
        
           onConfigureCellForAction = { [weak self] cell, action, indexPath in
               cell.setup(action.data?.title, detail: nil, image: action.data?.image)
               // The rest of the setup code...
           }
   }
   ```


I'm sorry for the long time without an answer, it could be too late but this might help somebody else.
