### ISSUE TITLE
how to handle a dismiss function

### ISSUE THREAD

**Issue by shindonghyeok** [xmartlabs/XLActionController#15]
is it possible to add? a dismiss handler to addAction function?? 

what i want to do is that  i want to do someting after dismiss actionController...

**Comment by junhohong** [comment]
There is no specific "dismiss" handler. If you need to change the hierarchy of your view controllers, you can dispatch it asynchronously to the main queue in the completion block. 

```
dispatch_async(dispatch_get_main_queue(), {
                self.presentViewController(self.imagePicker, animated: true, completion: nil)
})
```

If you do not do it this way, whatever you put in the completion block will run at the same time the view is tapped.

**Comment by m-revetria** [comment]
@shindonghyeok this seems to be related to issue #20 where actions' handlers are being executed before the action controller is dismissed. 

In PR #22 this behavior is changed, actions' handlers will be executed after the action controller has been dismissed. So you will be able to to do your stuff in the action handler block.
