### ISSUE TITLE
Skype dismiss speed 

### ISSUE THREAD

**Issue by junhohong** [xmartlabs/XLActionController#18]
Xcode 7.3, iOS9, newest XLActionController. 

Is there any way to alter the speed of dismissal of SkypeActionController? Changing the dismiss speed/velocity/damping in settings did not seem to do anything.

**Comment by m-revetria** [comment]
@junhohong in the case of the `SkypeActionController` these properties control how the background is faded out. This controller has its own custom animation when dismissing, it uses UIDynamics with a UIGravityBehavior. Then, the speed of the animation is determined by the `gravityBehavior` properties. You can try by setting a bigger value to `gravityBehavior.magnitude` (something like 50 makes it go away really fast)
