### ISSUE TITLE
Actionsheet Style

### ISSUE THREAD

**Issue by ajaysinghthakur** [xmartlabs/XLActionController#19]
is there any difference in selecting any of the style
public enum ActionStyle {
    case Default
    case Cancel
    case Destructive
}

because i don't think above struct used anywhere

**Comment by m-revetria** [comment]
@ajaysinghthakur, that property is intended to be used in the implementation of your custom actions cells. It is not used internally in the `ActionController` class. You can see an example of how it can be used in [PeriscopeActionController](https://github.com/xmartlabs/XLActionController/blob/master/Example/CustomActionControllers/Periscope.swift#L123) class.

Basically, we set `PeriscopeActionController.onConfigureCellForAction` to update cells style depending on the value of its `style` property:

```swift
onConfigureCellForAction = { [weak self] cell, action, indexPath in
    cell.setup(action.data, detail: nil, image: nil)
    // Other stuff
    cell.actionTitleLabel?.textColor = action.style == .Destructive ? UIColor(red: 210/255.0, green: 77/255.0, blue: 56/255.0, alpha: 1.0) : UIColor(red: 0.28, green: 0.64, blue: 0.76, alpha: 1.0)
}
```
