### ISSUE TITLE
Swift 3.0 Pod Support

### ISSUE THREAD

**Issue by mohpor** [xmartlabs/XLActionController#26]
Hi @m-revetria 
Just a reminder: The #24  has been merged with master and effectively updated this lib to Swift 3, but podspec and a tag is required to make it available through cocoapods.

Thanks again,
M.

**Comment by m-revetria** [comment]
@mohpor version 3.0.0 has been released https://github.com/xmartlabs/XLActionController/releases/tag/3.0.0 with support for Swift 3.

Thanks!
