### ISSUE TITLE
110 errors - Xcode 8, Swift 3

### ISSUE THREAD

**Issue by spiking** [xmartlabs/XLActionController#27]
Hello!

When I install XLActionController in my podfile and restart Xcode I get 110 errors. I thought it would be compatible with swift 3?

I tried it multiple times.

Do I have to specify branch?

**Comment by m-revetria** [comment]
Hi @spiking, Swift 3 is currently supported only in branch master. We will release a new version to Cocoapods shortly.

**Comment by spiking** [comment]
Hello!

Okey, thanks! How do I integrate the master branch in my project, without
cocoapods?

Regards
Adam



 Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=a.thuvesen@gmail.com&idSignature=22>

2016-09-26 17:07 GMT+02:00 Miguel Revetria <notifications@github.com>:

**Comment by m-revetria** [comment]
@spiking version 3.0.0 has been released https://github.com/xmartlabs/XLActionController/releases/tag/3.0.0 with support for Swift 3.

Thanks!
