### ISSUE TITLE
ActionCell.xib doesn't have an outlet for actionTitleLabelConstraintToContainer or actionTitleLabelConstraintToImageView

### ISSUE THREAD

**Issue by dmorrow** [xmartlabs/XLActionController#30]
XLActionController 3.0.0, XCode 8, iOS9

*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<XLActionController.ActionCell 0x7ff32660de50> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key actionTitleLabelConstraintToContainer.'

It appears that actionTitleLabelConstraintToContainer and actionTitleLabelConstraintToImageView don't have outlets in ActionCell.swift.

**Comment by m-revetria** [comment]
Hi @dmorrow, 

That change was introduced in version 2.1.0. You can see it more details here https://github.com/xmartlabs/XLActionController/releases/tag/2.1.0.

To fix the crash, you have to delete these outlets from your cell xibs. Take a look to this PR #23.

**Comment by dmorrow** [comment]
Thanks @m-revetria - this was a fresh install via Cocoapods.  Has this change not been included in 3.0.0

**Comment by m-revetria** [comment]
@dmorrow that change is included in 3.0.0. I just installed it in a totally new project and all  the examples provided are working fine for me.

Could you provide me with more info about the crash? Which is the failing action controller?

**Comment by dmorrow** [comment]
@m-revetria I'm not using one of the examples - I'm using the default ActionCell.xib that comes with the Cocoapod.

I am then creating a subclass like this
    import Foundation
    import XLActionController
    
    public class APSection: Section<String, Void> {
        public override init() {
            super.init()
            self.data = ()
        }
    }
    
    public class APHeader: UICollectionReusableView {
    
    lazy var label: UILabel = {
        let label = UILabel()
        label.textColor = UIColor(red: 171/255.0, green: 187/255.0, blue: 191/255.0, alpha: 1.0)
        label.numberOfLines = 0
        label.lineBreakMode = .byWordWrapping
        label.font = .systemFont(ofSize: 17.0)
        return label
    }()
    
    public override init(frame: CGRect) {
        super.init(frame: frame)
        backgroundColor = UIColor(white: 0.95, alpha: 1.0)
        addSubview(label)
    }
    
    required public init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    }
    
    public class APActionController: ActionController<ActionCell, String, APHeader, String, UICollectionReusableView, Void> {
    
    // override init in order to customize behavior and animations
    public override init(nibName nibNameOrNil: String? = nil, bundle nibBundleOrNil: Bundle? = nil) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        // customizing behavior and present/dismiss animations
        settings.behavior.hideOnScrollDown = false
        settings.animation.scale = nil
        settings.animation.present.duration = 0.25
        settings.animation.dismiss.duration = 0.25
        settings.animation.dismiss.options = .curveEaseIn
        settings.animation.dismiss.offset = 30
        
        // providing a specific collection view cell which will be used to display each action, height parameter expects a block that returns the cell height for a particular action.
        cellSpec = .nibFile(nibName:"ActionCell", bundle:Bundle(for:ActionCell.self), height: { _ in 60})
        // providing a specific view that will render each section header.
        sectionHeaderSpec = .cellClass(height: { _ in 5 })
        // providing a specific view that will render the action sheet header. We calculate its height according the text that should be displayed.
        headerSpec = .cellClass(height: { [weak self] (headerData: String) in
            guard let me = self else { return 0 }
            let label = UILabel(frame: CGRect(x: 0, y: 0, width: me.view.frame.width - 40, height: CGFloat.greatestFiniteMagnitude))
            label.numberOfLines = 0
            label.font = .systemFont(ofSize: 17.0)
            label.text = headerData
            label.sizeToFit()
            return label.frame.size.height + 20
            })
        
        // once we specify the views, we have to provide three blocks that will be used to set up these views.
        // block used to setup the header. Header view and the header are passed as block parameters
        onConfigureHeader = { [weak self] header, headerData in
            guard let me = self else { return }
            header.label.frame = CGRect(x: 0, y: 0, width: me.view.frame.width - 40, height: CGFloat.greatestFiniteMagnitude)
            header.label.text = headerData
            header.label.sizeToFit()
            header.label.center = CGPoint(x: header.frame.width  / 2, y: header.frame.height / 2)
        }
        // block used to setup the section header
        onConfigureSectionHeader = { sectionHeader, sectionHeaderData in
            sectionHeader.backgroundColor = UIColor(white: 0.95, alpha: 1.0)
        }
        // block used to setup the collection view cell
        onConfigureCellForAction = { [weak self] cell, action, indexPath in
            cell.setup(action.data, detail: nil, image: nil)
            cell.separatorView?.isHidden = indexPath.item == self!.collectionView.numberOfItems(inSection: indexPath.section) - 1
            cell.alpha = action.enabled ? 1.0 : 0.5
            cell.actionTitleLabel?.textColor = action.style == .destructive ? UIColor(red: 210/255.0, green: 77/255.0, blue: 56/255.0, alpha: 1.0) : UIColor(red: 0.28, green: 0.64, blue: 0.76, alpha: 1.0)
            }
        }
    
        required public init?(coder aDecoder: NSCoder) {
            fatalError("init(coder:) has not been implemented")
        }
    }

**Comment by m-revetria** [comment]
Hi @dmorrow!

Thanks for the provided code it was really helpful to figure out what was going on. PR #31 fix this crash.

I will release a new version with this in short.

Thanks!

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)
