### ISSUE TITLE
Incorrect insets in Spotify Example

### ISSUE THREAD

**Issue by codeOfRobin** [xmartlabs/XLActionController#34]
Before submitting issues ...

- [x] Make sure you are using XLActionController [latest release](https://github.com/xmartlabs/XLActionController/releases) or master branch version.
- [x] Make sure your Xcode version is the latest stable one.
- [x] Check if the issue was [already reported or fixed](https://github.com/xmartlabs/XLActionController/issues?utf8=%E2%9C%93&q=is%3Aissue). We add labels to each issue in order to easily find related issues. If you found a match add a brief comment "I have the same problem" or "+1".

When submitting issues, please provide the following information to help maintainers to fix the problem faster:

- Environment: XLActionController, Xcode and iOS version you are using. 
- In case of reporting errors, provide Xcode console output of stack trace or code compilation error.
- Any other additional detail such as example code that you think it would be useful to understand, reproduce and solve the problem.

Xcode 8, iOS 10, latest XLActionController

It looks like the top inset in the Spotify Example are set too high (here's a screenshot after the tableView has been pulled down).

![simulator screen shot 11-nov-2016 12 36 41 am](https://cloud.githubusercontent.com/assets/5009041/20190340/09bcdbe0-a7a7-11e6-82fd-a9aaecedb520.png)

A simple fix right now looks like increasing the offset by the height of the header.

`contentHeight = layoutAtts!.frame.origin.y + layoutAtts!.frame.size.height + 2 * (headerSpec?.height(headerData!))!`

when calculating contentHeight.

I'd make a PR, however I've made lots of other changes to the examples, so it wouldn't be too useful: https://github.com/codeOfRobin/xlactionviewcontroller

**Comment by m-revetria** [comment]
Hi @codeOfRobin, thanks for your contribution!

The issue is that the `contentHeight` is not taking into account the `cancelView`'s height. So, the change would be:

```swift
contentHeight = layoutAtts!.frame.origin.y + layoutAtts!.frame.size.height
if settings.cancelView.showCancel {
    contentHeight += settings.cancelView.height
}
```

This is ok for the spotify example. If you check the Spotify app, you will see it does something similar, but in other cases, maybe this is not the desired behavior. So, I'm going to add a new property to allow developers to change whether the action controller should hide or not behind `cancelView`

**Comment by m-revetria** [comment]
Hi @codeOfRobin! From now, if you set `settings.cancelView.hideCollectionViewBehindCancelView` property to `false` the collection view will stay above the cancel view all the time.

Thanks
