### ISSUE TITLE
Objective-C compatible 

### ISSUE THREAD

**Issue by Olympiloutre** [xmartlabs/XLActionController#38]
This framework is not usable in objective C. Is it possible to add a @objc prefix before main classes? Otherwise the only accessible classes are those which are subclasses of NSObjects. 

> A Swift class or protocol must be marked with the @objc attribute to be accessible and usable in Objective-C.

**Comment by RolandTolnay** [comment]
Has this been added recently? Seems like an easy update to solve a common issue

**Comment by Olympiloutre** [comment]
@RolandTolnay Added on November, still no updates. If you wonder how I overpass this, that's simple: I made my own classes in Objective C, I didn't use this pod. 
Actually it's really basic to reproduce it's functionning, it only needs UIViews UILabels and UIButtons put in the right order, it took me 1-2 days.

**Comment by mtnbarreto** [comment]
There are many structs and enums in swift that can not be converted to obj-c (in particular those that define the action controller items. ) and we do not have any intention to provide an obj-c compatible source code.
