### ISSUE TITLE
Use of unresolved identifier 'YoutubeActionController'?

### ISSUE THREAD

**Issue by Dbigshooter** [xmartlabs/XLActionController#39]
Hi there,

Just got the pod and trying to play around with it. I keep getting "Use of unresolved identifier '...'", no matter which controller I try to instantiate, for example:

let actionsheet = YoutubeActionController()

I've imported the lib and all should be fine, however it's not. What to do?

**Comment by m-revetria** [comment]
Hi @Dbigshooter, 

How did you install `XLActionController`?

If you're using cocoapods you have to include the subspec associated to the example that you want to use. For example, in order to have the YoutubeActionController available your `Podfile` should look similar to:

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

def app_pods
  pod 'XLActionController'
  pod 'XLActionController/Youtube'
end

target 'YourTarget' do
    app_pods
end
```

> Ensure you have run `pod install` with that configuration

**Comment by m-revetria** [comment]
Closing due to lack of response
