### ISSUE TITLE
Custom cancel button

### ISSUE THREAD

**Issue by RealBug** [xmartlabs/XLActionController#42]
Your component is great! 

I just regret that we can't customize the cancel button. 
In the example of spotify, if you want to put a button with title in black (white by default, you can not modify it) and add margins to the left and right), how can you do it? 

Thank you in advance

**Comment by RealBug** [comment]
Your component is great! I just regret that we can't customize the cancel button. In the example of spotify, if you want to put a button with title in black (white by default, you can not modify it) and add margins to the left and right), how can you do it?  thank you in advance

**Comment by RealBug** [comment]
![img_0589](https://cloud.githubusercontent.com/assets/4263673/20692294/3aa97f90-b5d7-11e6-95b3-e890f3c8c5b9.PNG)

**Comment by m-revetria** [comment]
Hi @RealBug, thanks for your contribution!

Right you can use a custom `cancelView` in a subclass of `XLActionController` by creating it in `viewDidLoad` **before calling super**. Take a look to the next code snippet:

```swift
open class CustomActionController: ActionController<CustomCell, ActionData, CustomHeaderView, SpotifyHeaderData, UICollectionReusableView, Void> {
   
    public override init(nibName nibNameOrNil: String? = nil, bundle nibBundleOrNil: Bundle? = nil) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)

        settings.cancelView.showCancel = true
        settings.cancelView.backgroundColor = .lightGray

        // Add all needed settings
    }

    open override func viewDidLoad() {
        cancelView = {
            let cancelView = UIView(frame: CGRect(x: 0, y: 0, width: view.bounds.size.width, height: settings.cancelView.height))
            cancelView.backgroundColor = settings.cancelView.backgroundColor

            let button = UIButton()
            button.backgroundColor = .white
            button.setTitle("Cancel", for: .normal)
            button.setTitleColor(.black, for: .normal)
            button.translatesAutoresizingMaskIntoConstraints = false

            cancelView.addSubview(button)
            cancelView.addConstraints(
                NSLayoutConstraint.constraints(withVisualFormat: "H:|-20-[button]-20-|", options: [], metrics: nil, views: ["button": button]) +
                NSLayoutConstraint.constraints(withVisualFormat: "V:|-5-[button]-5-|", options: [], metrics: nil, views: ["button": button])
            )

            return cancelView
        }()

        super.viewDidLoad()
    }

}
```

We are planning to add support for a `CancelViewSpec` in a future version, which will allow developers to completely customize the `cancelView`'s style similarly to how the header is defined. But for now you can do something similar to the code shown above.

**Comment by RealBug** [comment]
Awesome, thank you for your great work !
