### ISSUE TITLE
StatusBar hidden on iOS 10

### ISSUE THREAD

**Issue by RealBug** [xmartlabs/XLActionController#43]
Hi,

Just one little bug on iOS 10, the "status bar hidden" config doesn't work.
settings.statusBar.showStatusBar = false

Thx

**Comment by RealBug** [comment]
I found a solution : 
Put this in your view controller : 
    open override var prefersStatusBarHidden: Bool  {
        get {
            return self.presentedViewController != nil && !self.presentedViewController!.isBeingDismissed
        }
    }

**Comment by SanjithKanagavel** [comment]
@RealBug color change is not happening. 
open override var preferredStatusBarStyle: UIStatusBarStyle {
     return .lightContent
}

doesn't work.
