### ISSUE TITLE
Can the Controller be presented on top part of the screen

### ISSUE THREAD

**Issue by ilandbt** [xmartlabs/XLActionController#46]
Can the controller be presented on the top part of the screen instead of the bottom?

Thanks

**Comment by m-revetria** [comment]
Hi @ilandbt, you can show the actions on the top part of the screen by overriding `onWillPresentView` and `performCustomDismissingAnimation(_:presentingView:)`. See the code below:

```swift
    open override func onWillPresentView() {
        super.onWillPresentView()
        collectionView.contentInset.top = 0
        collectionView.frame.origin.y = -view.bounds.height
    }

    open override func performCustomDismissingAnimation(_ presentedView: UIView, presentingView: UIView) {
        super.performCustomDismissingAnimation(presentedView, presentingView: presentingView)
        collectionView.frame.origin.y = -view.bounds.height
    }
```

With that changes you will get this:

![action_controller_on_top](https://cloud.githubusercontent.com/assets/4791678/22690415/7a2fed10-ed14-11e6-92eb-32dc74884908.gif)

**Comment by m-revetria** [comment]
Closing due to lack of response
