### ISSUE TITLE
Can we change the text or background color of individual Actions depending upon some condition?

### ISSUE THREAD

**Issue by chaoticbit** [xmartlabs/XLActionController#48]
- Xcode 8 Swift 3 iOS 10.2 
- using YouTubeActionController

I have a situation where depending upon some condition I need to change either text or background color of an individual Action.

For eg. I have a list of books in which a book can be added to reading list and on tap of that I display action sheet where there are 4 actions. If that book is already added to reading list I have to show the reading list action in green color and if not added then default color. 

Can this be possible? and if so then can you show me how to do it?
Thanks

**Comment by m-revetria** [comment]
Hi @chaoticbit,

If you are using the same cell for the actions that you want to change the text or background color, you can use the callback function `onConfigureCellForAction`. This callback is called for each row each time it's about to be shown. You can set this block in your `ActionController` subclass' constructor, like bellow:

```swift
public override init(nibName nibNameOrNil: String? = nil, bundle nibBundleOrNil: NSBundle? = nil) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)

    // Do other setup    

   onConfigureCellForAction = { cell, action, indexPath in
       // `action.data` will have the type you specified in the definition of your action controller class
       cell.backgroundColor = action.data.isAdded ? UIColor.green : UIColor.red
   }
}
```

Regards

**Comment by m-revetria** [comment]
Closing due to lack of response
