### ISSUE TITLE
SkypeActionController ContextView background color

### ISSUE THREAD

**Issue by akotulu** [xmartlabs/XLActionController#50]
Hey, thanks for the great library. I'm using the out of the box Skype action controller, but it seems I can't change the background color without copying the source to my own project. Would be awesome, if it could be made changeable either from constructor or a class variable.

**Comment by m-revetria** [comment]
Hey @akotulu,

You're right, right now there is no way to customize the Skype action controller's background color. We are going to add a way to customize it.

Thanks
