### ISSUE TITLE
Header in YoutubeActionController

### ISSUE THREAD

**Issue by pareekkhushboo77** [xmartlabs/XLActionController#51]
How to add a custom view with list of actions, like image attached.
![screen shot 2017-04-17 at 3 58 01 pm](https://cloud.githubusercontent.com/assets/16894064/25086642/ad869224-2386-11e7-9c32-3f4804ef809b.png)

Please help.

**Comment by m-revetria** [comment]
Hi @pareekkhushboo77,

To show an action controller with multiple options and a header you can use the `SpotifyActionController` as example. It looks like the image below and with some effort you will be able to show a header similar to the one you shown.

![image](https://cloud.githubusercontent.com/assets/4791678/25635880/ff8ba232-2f55-11e7-9b1c-3344c7c1d284.png)

**Comment by m-revetria** [comment]
Closing due to lack of response
