### ISSUE TITLE
navbar height is resizing in ios 11

### ISSUE THREAD

**Issue by pprevalon** [xmartlabs/XLActionController#64]
On ios 11 it look like the navBar height resize when the actionSheet shows. Im using the twitter actionSheet.

![renderedimage](https://user-images.githubusercontent.com/19171619/31016814-3bcb53b4-a4f4-11e7-9406-7336c65c4ea9.PNG)

**Comment by m-revetria** [comment]
Hi @pprevalon,

As the view controller containing the navigation bar is being scaled in the middle of the animation to show the action controller the navigation bar is not integrated with the status bar.

In the mean time, you can try either one of the following options:
* prevent the presenting view controller from being scaled
   ```swift
   // In your ActionController class
   public override init(nibName nibNameOrNil: String? = nil, bundle nibBundleOrNil: Bundle? = nil) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        settings.animation.scale = nil // Disable scaling
       // your stuff
   }
   ```
> If you are using TwitterActionController, you'll need to inherit from it in order to disable scaling.

* dismiss navigation bar before presenting action controller and showing it back when action controller is closed:
   ```swift
   navigationController?.setNavigationBarHidden(true, animated: true)
   let actionController = TwitterActionController()
   actionController.addAction(Action(ActionData(title: “Xmartlabs”, subtitle: “@xmartlabs”, image: UIImage(named: “tw-xmartlabs”)!), style: .default, handler: { [weak self] action in
       self?.navigationController?.setNavigationBarHidden(false, animated: true)
   }))
   ```
