### ISSUE TITLE
iPhone X home indicator over XLActionController

### ISSUE THREAD

**Issue by jfredsilva** [xmartlabs/XLActionController#67]
With the iPhone X, the home indicator is appearing over the last cell.
The best way would be to add the bottom constraints to the bottom safe area.

**Comment by m-revetria** [comment]
@jfredsilva we are working on fix the issues on iPhone X. Meanwhile you can change the bottom inset from you custom ActionController in this way:

```swift
    public override init(nibName nibNameOrNil: String? = nil, bundle nibBundleOrNil: Bundle? = nil) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        collectionView.contentInset = UIEdgeInsets.init(top: 0, left: 0, bottom: 30, right: 0)
        // your stuff
}
```

**Comment by Vincent-Loi** [comment]
@m-revetria When will the fixes [bug/67-iphone-x-support] be merged to master?

**Comment by m-revetria** [comment]
Should be already fixed on master branch. We will release a new version shortly!
