### ISSUE TITLE
Unnecessary insets on iOS 11

### ISSUE THREAD

**Issue by lnorton** [xmartlabs/XLActionController#68]
iOS 11 is inserting scroll view insets related to the safe area, which put more whitespace in the collection view than is necessary, pushing content off-screen and adding unnecessary scrolling.

I was able to correct this by adding the following to my subclass of ActionController:

```
if #available(iOS 11.0, *) {
  collectionView.contentInsetAdjustmentBehavior = .never
}
```

The code likely needs to be updated to account for the safe area changes, as well as the bottom area on iPhone X.

**Comment by mtnbarreto** [comment]
Hi @lnorton ! The code was optimized for iphoneX. Could you please provide feedback?
