### ISSUE TITLE
scrollViewDidScroll never called

### ISSUE THREAD

**Issue by mazodeveloper** [xmartlabs/XLActionController#71]
I have created a controller that extend from ActionController and everything works fine, but im trying to use the scrollViewDidScroll but i can't detect the event when the user scroll.

i have implemented the delegate
collectionView.delegate = self
but the scrollViewDidScroll method never is called.

how can i use this method?? i need to change the scrollView indicator design.

**Comment by m-revetria** [comment]
Hi @mazodeveloper,

You have to annotate your function with `@objc`. This is needed due to `ActionController` class (UICollectionView's delegate) does not implement it.

More info:
* https://bugs.swift.org/browse/SR-2817
* https://stackoverflow.com/a/39416386/1070393

**Comment by m-revetria** [comment]
I'm closing this due to lack of response
