### ISSUE TITLE
iOS 11 Crash !

### ISSUE THREAD

**Issue by fadylateef** [xmartlabs/XLActionController#75]
An error occurred using iOS 11 devices, Please update your library.
The problem caused on this line.
`return animator.items(in: rect) as? [UICollectionViewLayoutAttributes]`

And the error log is 
`Fatal error: NSArray element failed to match the Swift Array Element type`

Looks like a problem with casting animator.items

**Comment by HyunjoonKo** [comment]
I also had the same problem and modified the code.

```
override open func layoutAttributesForElements(in rect: CGRect) -> [UICollectionViewLayoutAttributes]? {
        guard let animator = dynamicAnimator else {
            return super.layoutAttributesForElements(in: rect)
        }
        
        if let items = animator.items(in: rect) as? [AnyObject] {
            return items.filter{ $0 is UICollectionViewLayoutAttributes }.map{ $0 as! UICollectionViewLayoutAttributes }
        }

        return nil
        //return animator.items(in: rect) as? [UICollectionViewLayoutAttributes]
}
```

**Comment by m-revetria** [comment]
Hi guys, sorry for the delay to respond. We've been a bit busy here, I hope you can understand.

I just made a PR with the suggested fix, thanks!

Regards.
