### ISSUE TITLE
Wrong bottom inset

### ISSUE THREAD

**Issue by BlackSelf** [xmartlabs/XLActionController#86]
I used to set `collectionView.contentInset.bottom` to some value and it used to add the bottom inset to the sheet. But after the 4.0.1 it is not the case. I don't know if it's intended to work that way. If it is, then how do I add bottom inset. If it is a bug, then changing line `681` in `ActionController.swift`:
from
`collectionView.contentOffset.y = -height + contentHeight + safeAreaInsets.bottom`
to
`collectionView.contentOffset.y = -height + contentHeight + bottomInset`
might solve the problem.

**Comment by SergejLogis** [comment]
Quite sure it is related to the issue I described in https://github.com/xmartlabs/XLActionController/issues/85
:) 👍
