### ISSUE TITLE
how to use this library for Objective-C project?

### ISSUE THREAD

**Issue by MallikarjunH** [xmartlabs/XLActionController#89]

**Comment by mtnbarreto** [comment]
Hi @MallikarjunH , Last time i use objective-c was 4 years ago. However, i think that there still are some kind of compatibility so it should be possible. 

Did you try something?

**Comment by Mallikarjun-Hanagandi** [comment]
Yes, I tried. I am using this library in my swift project. This is an awesome library. Thank you for this.
