### ISSUE TITLE
Cancel actions on hideOnTap and hideOnScrollDown?

### ISSUE THREAD

**Issue by SuperTango** [xmartlabs/XLActionController#97]
Is it possible to get the hideOnTap and hideOnScrollDown to call the "cancel" action?  We have a controller that needs to perform actions when cancel is tapped (which works fine with the completion block in the cancel button), but also the same actions when the XLActionController is dismissed via tap and swipe.

Thanks!

**Comment by mtnbarreto** [comment]
In this case you should override `open func dismiss(_ completion: (() -> ())? = nil)` .

Hope it helps!

**Comment by SuperTango** [comment]
Cool.  Though, dismiss() is called whenever any action is tapped. How do I know which action was tapped so I know to only call the cancel handler when no other action was tapped?
